#!/bin/sh
#
# A hook to verify what is about to be committed. Called by "git commit" with
# no arguments.  The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.

echo "running hook $0"

# Redirect output to stderr.
exec 1>&2

# Is this the initial commit, handle diff differently if so
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --

# If there formatting doesn't conform to our standard
exec black --line-length 80 --check

# If syntax doesn't conform to our standard
exec pylint
